version: "3.9"

services:
  redis:
    image: "redis:7.0.2"
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command: "redis-server --save 60 1 --loglevel warning"

  bot:
    build: .
    environment:
      - POKERBOT_TOKEN=$POKERBOT_TOKEN
      - POKERBOT_REDIS_HOST=redis

volumes:
  redis_data:
